apiVersion: v1
kind: Secret
metadata:
  name: mongo-pass
type: Opaque
data:
  env: 
  - name: MONGO_ROOT_USERNAME
    value: admin
  - name: MONGO_ROOT_PASSWORD
    value: c3VwZXJzZWNyZXRwYXNzd29yZA==