apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: karsa-mongo
spec:
  selector:
    matchLabels:
      app: karsa-mongo
  serviceName: mongo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: karsa-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: ghcr.io/faridfirdautama/karsajobs:1.0.0
        name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        ports:
        - containerPort: 27018
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: configmap-volume
          mountPath: /config
          readOnly: true
        - name: secret-volume
          mountPath: /etc/mongo-credentials
          readOnly: true

      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      - name: configmap-volume
        configMap:
          name: mongo-config
          items:
            - key: "mongo.config"
      - name: secret-volume
        secret:
          secretName: mongo-pass
          optional: true