# set the version
version: '3.8'

# listed all 2 services
services:
  item-app:
    image: ghcr.io/faridfirdautama/item-app:1.0.0
    command: npm start
    ports:
      - "80:8080"
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - item-db

  item-db:
    image: mongo:3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123

    volumes:
      - app-db:/data/db

volumes:
  app-db:
