version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq-docker'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_network
  
  # order-service:
  #   image: ghcr.io/faridfirdautama/order-service:1.0.0
  #   container_name: orderService-docker
  #   depends_on:
  #     - rabbitmq
  #   ports:
  #     - 3000:3000
  #   command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
  #   environment:
  #     PORT: 3000
  #     AMQP_URL: amqp://guest:guest@rabbitmq:5672
  #   networks:
  #     - rabbitmq_network
      
  
  # shipping-service:
  #   image: ghcr.io/faridfirdautama/shipping-service:1.0.0
  #   container_name: shippingService-docker
  #   depends_on:
  #     - rabbitmq
  #   ports:
  #     - 3001:3001
  #   command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
  #   environment:
  #     PORT: 3001
  #     AMQP_URL: amqp://guest:guest@rabbitmq:5672
  #   networks:
  #     - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge