apiVersion: v1
kind: Service
metadata:
  name: karsajobs
  labels:
    app: karsa-backend
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 9090
    nodePort: 30004
    targetPort: 8080
  selector:
    app: karsa-backend