apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui
  labels:
    app: karsa-frontend
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30003
    targetPort: 8000
  selector:
    app: karsa-frontend