apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsa-frontend
  labels:
    app: karsa-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: karsa-frontend
  template:
    metadata:
      labels:
        app: karsa-frontend
        tier: frontend
    spec:
      containers:
      - name: karsajobs-ui
        image: ghcr.io/faridfirdautama/karsajobs-ui:1.0.0
        ports:
          - containerPort: 8000